// Generated by nuxt-seo-utils

import type { RobotsContext } from '#robots/types'

declare module 'nitropack/types' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}

declare module 'nitropack' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}


declare module '@nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

declare module 'nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@7.0.18_h3@1._c13c7ee0aff289cbd2278c741d53dfb1/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

export {}
