// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.9_@unhe_41b060ef88436e380c94f1795829b7d5/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@5.0.9_@unhe_41b060ef88436e380c94f1795829b7d5/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
