import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ContentEnCollectionItem extends PageCollectionItemBase {
    sitemap?: {
    loc?: string;
    lastmod?: string;
    changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
    priority?: number;
    images?: {
      loc: string;
      caption?: string;
      geo_location?: string;
      title?: string;
      license?: string;
    }[];
    videos?: {
      content_loc: string;
      player_loc?: string;
      duration?: string;
      expiration_date?: string;
      rating?: number;
      view_count?: number;
      publication_date?: string;
      family_friendly?: boolean;
      tag?: string;
      category?: string;
      restriction?: {
      relationship?: "allow";
      value?: string;
      };
      gallery_loc?: string;
      price?: string;
      requires_subscription?: boolean;
      uploader?: string;
    }[];
    };
    robots?: string | boolean;
    head?: {
    meta: {
      [k: string]: unknown;
    }[];
    script: {
      [k: string]: unknown;
    }[];
    };
    schemaOrg?:
    | {
      [k: string]: unknown;
      }
    | (
      | {
        [k: string]: unknown;
        }
      | {
        [k: string]: unknown;
        }[]
      );
    ogImage?: {
    url?: string;
    component?: string;
    props: {
      [k: string]: unknown;
    };
    };
    title: string;
    description: string;
    date: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ContentFrCollectionItem extends PageCollectionItemBase {
    sitemap?: {
    loc?: string;
    lastmod?: string;
    changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
    priority?: number;
    images?: {
      loc: string;
      caption?: string;
      geo_location?: string;
      title?: string;
      license?: string;
    }[];
    videos?: {
      content_loc: string;
      player_loc?: string;
      duration?: string;
      expiration_date?: string;
      rating?: number;
      view_count?: number;
      publication_date?: string;
      family_friendly?: boolean;
      tag?: string;
      category?: string;
      restriction?: {
      relationship?: "allow";
      value?: string;
      };
      gallery_loc?: string;
      price?: string;
      requires_subscription?: boolean;
      uploader?: string;
    }[];
    };
    robots?: string | boolean;
    head?: {
    meta: {
      [k: string]: unknown;
    }[];
    script: {
      [k: string]: unknown;
    }[];
    };
    schemaOrg?:
    | {
      [k: string]: unknown;
      }
    | (
      | {
        [k: string]: unknown;
        }
      | {
        [k: string]: unknown;
        }[]
      );
    ogImage?: {
    url?: string;
    component?: string;
    props: {
      [k: string]: unknown;
    };
    };
    title: string;
    description: string;
    date: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ArticlesEnCollectionItem extends PageCollectionItemBase {
    sitemap?: {
    loc?: string;
    lastmod?: string;
    changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
    priority?: number;
    images?: {
      loc: string;
      caption?: string;
      geo_location?: string;
      title?: string;
      license?: string;
    }[];
    videos?: {
      content_loc: string;
      player_loc?: string;
      duration?: string;
      expiration_date?: string;
      rating?: number;
      view_count?: number;
      publication_date?: string;
      family_friendly?: boolean;
      tag?: string;
      category?: string;
      restriction?: {
      relationship?: "allow";
      value?: string;
      };
      gallery_loc?: string;
      price?: string;
      requires_subscription?: boolean;
      uploader?: string;
    }[];
    };
    robots?: string | boolean;
    head?: {
    meta: {
      [k: string]: unknown;
    }[];
    script: {
      [k: string]: unknown;
    }[];
    };
    schemaOrg?:
    | {
      [k: string]: unknown;
      }
    | (
      | {
        [k: string]: unknown;
        }
      | {
        [k: string]: unknown;
        }[]
      );
    ogImage?: {
    url?: string;
    component?: string;
    props: {
      [k: string]: unknown;
    };
    };
    title: string;
    description: string;
    date: string;
    image: string;
    readingTime: string;
    tags: string[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ArticlesFrCollectionItem extends PageCollectionItemBase {
    sitemap?: {
    loc?: string;
    lastmod?: string;
    changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
    priority?: number;
    images?: {
      loc: string;
      caption?: string;
      geo_location?: string;
      title?: string;
      license?: string;
    }[];
    videos?: {
      content_loc: string;
      player_loc?: string;
      duration?: string;
      expiration_date?: string;
      rating?: number;
      view_count?: number;
      publication_date?: string;
      family_friendly?: boolean;
      tag?: string;
      category?: string;
      restriction?: {
      relationship?: "allow";
      value?: string;
      };
      gallery_loc?: string;
      price?: string;
      requires_subscription?: boolean;
      uploader?: string;
    }[];
    };
    robots?: string | boolean;
    head?: {
    meta: {
      [k: string]: unknown;
    }[];
    script: {
      [k: string]: unknown;
    }[];
    };
    schemaOrg?:
    | {
      [k: string]: unknown;
      }
    | (
      | {
        [k: string]: unknown;
        }
      | {
        [k: string]: unknown;
        }[]
      );
    ogImage?: {
    url?: string;
    component?: string;
    props: {
      [k: string]: unknown;
    };
    };
    title: string;
    description: string;
    date: string;
    image: string;
    readingTime: string;
    tags: string[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ProjectsEnCollectionItem extends DataCollectionItemBase {
    name: string;
    image: string;
    link: string;
    release: string;
    date: string;
    featured?: boolean;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ProjectsFrCollectionItem extends DataCollectionItemBase {
    name: string;
    image: string;
    link: string;
    release: string;
    date: string;
    featured?: boolean;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface StackCollectionItem extends DataCollectionItemBase {
    items: {
    name: string;
    link: string;
    icon: string;
    }[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface FaqEnCollectionItem extends DataCollectionItemBase {
    title: string;
    subtitle: string;
    faqQuestions: {
    title: string;
    questions: {
      label: string;
      content: string;
    }[];
    }[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface FaqFrCollectionItem extends DataCollectionItemBase {
    title: string;
    subtitle: string;
    faqQuestions: {
    title: string;
    questions: {
      label: string;
      content: string;
    }[];
    }[];
  }
  

  interface PageCollections {
    content_en: ContentEnCollectionItem
    content_fr: ContentFrCollectionItem
    articles_en: ArticlesEnCollectionItem
    articles_fr: ArticlesFrCollectionItem
  }

  interface Collections {
    content_en: ContentEnCollectionItem
    content_fr: ContentFrCollectionItem
    articles_en: ArticlesEnCollectionItem
    articles_fr: ArticlesFrCollectionItem
    projects_en: ProjectsEnCollectionItem
    projects_fr: ProjectsFrCollectionItem
    stack: StackCollectionItem
    faq_en: FaqEnCollectionItem
    faq_fr: FaqFrCollectionItem
  }
}
